version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    build: db/.
    volumes:
      - ./db/data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api
    restart: always
    build: api/.
    volumes:
      - ./api:/usr/src/musicroom
      - /usr/src/musicroom/node_modules
    ports:
      - '4242:4242'
    links:
      - mongo
  # react-front:
  #   container_name: react
  #   restart: always
  #   build: react-front/.
  #   volumes:
  #     - ./react-front:/usr/src/react
  #     - /usr/src/react/node_modules
  #   links:
  #     - api
  #   ports:
  #     - '80:80'
